const SLOT_STATUS = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  PENDING: 'PENDING',
  OPEN_HOUR: 'OPEN_HOUR',
  PLANNING: 'PLANNING',
  APPOINTMENT: 'APPOINTMENT',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
});

export default SLOT_STATUS;
